name: 构建检查流水线

on:
  push:
    branches: 
      - master
      - release/*
      - fix/*
      - feature/*
  pull_request:
    branches:
      - master
      - release/*
      - fix/*
      - feature/*

jobs:
  service_build_check:
    name: Service 构建检查
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: ESLint 检查
        run: cd packages/local-transfer-service && pnpm run lint
      - name: 单元测试检查
        run: cd packages/local-transfer-service && pnpm run test
      - name: 构建检查
        run: cd packages/local-transfer-service && pnpm run build
  app_build_check:
    name: App 构建检查
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: ESLint 检查
        run: cd packages/local-transfer-app && pnpm run lint
      - name: Service 生成
        run: cd packages/local-transfer-service && pnpm run build
      - name: 构建检查
        run: cd packages/local-transfer-app && pnpm run build

      

