name: Master PR 流水线


on:
  push:
    branches: 
      - master

jobs:
  build_check:
    name: 构建检查
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Service 构建
        run: cd packages/local-transfer-service && pnpm run build
      - name: App 构建
        run: cd packages/local-transfer-app && pnpm run build
  changelog:
    needs:
      - build_check
    name: Changeset 版本生成
    # 这里判断仓库owner是否是我自己，为了避免别人 fork 仓库触发
    if: ${{ github.repository_owner == 'wengx00' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # 设置 pnpm 指定版本7.0，不然会报错
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm install
      # 使用changesets/action自动创建 PR 或者发布
      - name: 自动更改版本
        id: changesets
        uses: changesets/action@v1
        with:
          # 执行更新版本和发布的命令
          version: pnpm run version-package
          commit: 'chore: auto change verion'
          title: 'chore: auto change verion'
        env:
          # GITHUB_TOKEN 是 CI 里自带的默认 token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

