name: Master PR 流水线


on:
  on:
  push:
    branches: 
      - master

jobs:
  changelog:
    name: Changelog PR or Release
    # 这里判断仓库owner是否是我自己，为了避免别人 fork 仓库触发
    if: ${{ github.repository_owner == 'wengx00' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 设置 pnpm 指定版本7.0，不然会报错
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ^7.0

      # 设置 Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      # 安装依赖
      - name: Install dependencies
        run: pnpm install
      - name: Service 生成
        run: cd packages/local-transfer-service && pnpm run build
      - name: App 生成
        run: cd packages/local-transfer-app && pnpm run build
      # 使用changesets/action自动创建 PR 或者发布
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          # 执行更新版本和发布的命令
          version: pnpm run version-package
          commit: 'chore: auto change verion'
          title: 'chore: auto change verion'
        env:
          # GITHUB_TOKEN 是 CI 里自带的默认 token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

